import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // guideSidebar: [{ type: 'autogenerated', dirName: '.' }],

  guideSidebar: [
    'getting-started/index',
    'concepts',
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Build with FlowGen',
          items: ['guides/build/index'],
        },
        {
          type: 'category',
          label: 'Using FlowGen',
          items: ['guides/using/api/index', 'guides/using/embed/index'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/human-in-loop/index',
        'examples/ask-planner/index',
        'examples/search-n-write/index',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      items: ['advanced-guides/extend/index'],
    },
  ],
};

export default sidebars;
